<ul class="flex justify-around list-none md:mx-64">
    <li>
        <a
            href="https://twitter.com/isAdamBailey"
            aria-label="twitter"
            target="_blank"
        >
            <svg
                class="block"
                fill="currentColor"
                role="img"
                aria-hidden="true"
                width="30"
                height="30"
            >
                <use
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    xlink:href="./assets/img/icons.svg#icon-twitter"
                />
            </svg>
        </a>
    </li>
    <li class="ml-4">
        <a
            href="https://github.com/Owlnofeathers"
            aria-label="github"
            target="_blank"
        >
            <svg
                class="block"
                fill="currentColor"
                role="img"
                aria-hidden="true"
                width="40"
                height="40"
            >
                <use
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    xlink:href="./assets/img/icons.svg#icon-github"
                />
            </svg>
        </a>
    </li>
    <li class="ml-2">
        <a
            href="https://www.linkedin.com/in/adambailey2/"
            aria-label="linkedin"
            target="_blank"
        >
            <svg
                class="block"
                fill="currentColor"
                role="img"
                aria-hidden="true"
                width="27"
                height="27"
            >
                <use
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    xlink:href="./assets/img/icons.svg#icon-linkedin"
                />
            </svg>
        </a>
    </li>
    <li class="ml-5">
        <a
            href="mailto:adam@adambailey.io"
            aria-label="email"
            target="_blank"
        >
            <svg
                class="block"
                fill="currentColor"
                role="img"
                aria-hidden="true"
                width="30"
                height="30"
            >
                <use
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    xlink:href="./assets/img/icons.svg#icon-email"
                />
            </svg>
        </a>
    </li>
</ul>